name: Run Konveyor release-0.1 nightly tests

on:
  schedule:
    - cron: "5 3 * * *"
  workflow_dispatch:

jobs:
  release-0_1-nightly:
    uses: ./.github/workflows/global-ci.yml
    with:
      tag: release-0.1
      api_tests_ref: 95c17ea090d50c0c623aa7d43168f6ca8fe26a88
      ui_tests_ref: mta_6.1.1
      run_ui_tests: true
